# This file used to be auto-generated by cabal2nix. Edit with care.

{ cabal, aeson, attoparsec, caseInsensitive, certificate
, cryptoRandom, dataDefault, hslogger, httpConduit, httpKit
, httpTypes, interpolatedstringPerl6, mtl, network
, optparseApplicative, postgresqlSimple, resourcePool, safe, SHA
, split, stringConversions, time, tls, unorderedContainers
, utf8String, x509, yaml, cabalDrvArgs
, src
}:

cabal.mkDerivation (self: cabalDrvArgs // {
  pname = "sproxy";
  version = "0.8.0";
  inherit src;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson attoparsec caseInsensitive certificate cryptoRandom
    dataDefault hslogger httpConduit httpKit httpTypes
    interpolatedstringPerl6 mtl network optparseApplicative
    postgresqlSimple resourcePool safe SHA split stringConversions time
    tls unorderedContainers utf8String x509 yaml
  ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
